### ISSUE TITLE
Incorrect line numbers in stacktraces

### ISSUE THREAD

**Issue by SubJunk** [UniversalMediaServer/api#119]
In our tests we are getting impossible line numbers, possibly due to `ts-node` (that's a guess).
e.g.

```
console.error
    Error: title is required
        at Object.exports.getBySanitizedTitle (/home/travis/build/UniversalMediaServer/api/src/controllers/media.ts:3018:11)
        at /home/travis/build/UniversalMediaServer/api/src/routes/media.ts:314:25
        at dispatch (/home/travis/build/UniversalMediaServer/api/node_modules/koa-compose/index.js:42:32)
        at /home/travis/build/UniversalMediaServer/api/node_modules/koa-router/lib/router.js:368:16
        at dispatch (/home/travis/build/UniversalMediaServer/api/node_modules/koa-compose/index.js:42:32)
        at /home/travis/build/UniversalMediaServer/api/node_modules/koa-compose/index.js:34:12
        at dispatch (/home/travis/build/UniversalMediaServer/api/node_modules/koa-router/lib/router.js:373:31)
        at dispatch (/home/travis/build/UniversalMediaServer/api/node_modules/koa-compose/index.js:42:32)
        at bodyParser (/home/travis/build/UniversalMediaServer/api/node_modules/koa-bodyparser/index.js:95:11)
        at processTicksAndRejections (internal/process/task_queues.js:97:5)
        at /home/travis/build/UniversalMediaServer/api/src/app.ts:624:3
        at /home/travis/build/UniversalMediaServer/api/src/app.ts:584:5
```

**Comment by js-kyle** [comment]
After a veeeeeery long look into this, I tracked it down to a bug in Jest.

Jest issue: https://github.com/facebook/jest/issues/5739

As it happens, a fix for this has just been merged to Jest. It will be available in whatever version is published which is greater than this one https://github.com/facebook/jest/blob/master/CHANGELOG.md#2540

I confirmed it is the same issue, as I did a build without code coverage, and I got correct stack traces https://travis-ci.org/github/UniversalMediaServer/api/builds/678905203

Can prolly close this as dependabot will update up when a version is there
