### ISSUE TITLE
Season cast NaN to number error

### ISSUE THREAD

**Issue by SubJunk** [UniversalMediaServer/api#401]
This error is from the logs:

```
Error: SeriesMetadata validation failed: totalSeasons: Cast to Number failed for value "NaN" at path "totalSeasons"
    at ValidationError.inspect (node_modules/mongoose/lib/error/validation.js:47:26)
    at formatValue (internal/util/inspect.js:723:31)
    at inspect (internal/util/inspect.js:289:10)
    at formatWithOptionsInternal (internal/util/inspect.js:1918:40)
    at formatWithOptions (internal/util/inspect.js:1802:10)
    at Object.Console.<computed> (internal/console/constructor.js:295:10)
    at Object.warn (internal/console/constructor.js:305:61)
    at src/app.ts:48:15
```

**Comment by js-kyle** [comment]
I'm not looking at this, but I just had a thought it might be because some places use `parseInt` rather than `Number`

**Comment by SubJunk** [comment]
Yeah I think it comes from https://github.com/worr/node-imdb-api/blob/master/src/imdb.ts#L443
