### ISSUE TITLE
Log error: Cannot read property 'trim' of undefined

### ISSUE THREAD

**Issue by SubJunk** [UniversalMediaServer/api#515]
At a glance we are passing something empty to that module, but haven't looked

```
TypeError: Cannot read property 'trim' of undefined
    at LibID.parseResponse (/root/api/node_modules/opensubtitles-api/lib/identify.js:44:80)
    at /root/api/node_modules/opensubtitles-api/index.js:201:37
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at OpenSubtitles.osAPI.identify (/root/api/src/services/opensubtitles.ts:10:12)
    at Object.getFromOpenSubtitles (/root/api/src/services/external-api-helper.ts:236:33)
    at Object.getVideo (/root/api/src/controllers/media.ts:428:29)
    at /root/api/src/routes/media.ts:34:3
    at bodyParser (/root/api/node_modules/koa-bodyparser/index.js:95:5)
    at /root/api/src/app.ts:73:3
    at /root/api/src/app.ts:66:3
    at /root/api/src/app.ts:30:5
```

**Comment by SubJunk** [comment]
This seems to be a third party bug so I made an issue at https://github.com/vankasteelj/opensubtitles-api/issues/58
