### ISSUE TITLE
Log error: Cannot read property 'length' of undefined

### ISSUE THREAD

**Issue by SubJunk** [UniversalMediaServer/api#516]
```
TypeError: Cannot read property 'length' of undefined
    at /root/api/node_modules/opensubtitles-api/index.js:190:52
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at OpenSubtitles.osAPI.identify (/root/api/src/services/opensubtitles.ts:10:12)
    at Object.getFromOpenSubtitles (/root/api/src/services/external-api-helper.ts:236:33)
    at Object.getVideo (/root/api/src/controllers/media.ts:428:29)
    at /root/api/src/routes/media.ts:34:3
    at bodyParser (/root/api/node_modules/koa-bodyparser/index.js:95:5)
    at /root/api/src/app.ts:73:3
    at /root/api/src/app.ts:66:3
    at /root/api/src/app.ts:30:5
```

**Comment by SubJunk** [comment]
Another third party one https://github.com/vankasteelj/opensubtitles-api/issues/59
