### ISSUE TITLE
Log error: E11000 duplicate key error collection

### ISSUE THREAD

**Issue by SubJunk** [UniversalMediaServer/api#517]
```
MongoError: E11000 duplicate key error collection: series_metadata index: imdbID_1 dup key: { imdbID: "tt6768600" }
    at Function.create (/root/api/node_modules/mongodb/lib/core/error.js:57:12)
    at toError (/root/api/node_modules/mongodb/lib/utils.js:123:22)
    at /root/api/node_modules/mongodb/lib/operations/common_functions.js:258:39
    at handler (/root/api/node_modules/mongodb/lib/core/sdam/topology.js:944:24)
    at /root/api/node_modules/mongodb/lib/cmap/connection_pool.js:350:13
    at handleOperationResult (/root/api/node_modules/mongodb/lib/core/sdam/server.js:558:5)
    at MessageStream.messageHandler (/root/api/node_modules/mongodb/lib/cmap/connection.js:277:5)
    at MessageStream.emit (events.js:315:20)
    at MessageStream.EventEmitter.emit (domain.js:467:12)
    at processIncomingData (/root/api/node_modules/mongodb/lib/cmap/message_stream.js:144:12)
    at MessageStream._write (/root/api/node_modules/mongodb/lib/cmap/message_stream.js:42:5)
    at writeOrBuffer (internal/streams/writable.js:358:12)
    at MessageStream.Writable.write (internal/streams/writable.js:303:10)
    at Socket.ondata (internal/streams/readable.js:719:22)
    at Socket.emit (events.js:315:20)
    at Socket.EventEmitter.emit (domain.js:467:12) {
  driver: true,
  index: 0,
  code: 11000,
  keyPattern: { imdbID: 1 },
  keyValue: { imdbID: 'tt6768600' }
}
```

**Comment by SubJunk** [comment]
I'm also receiving this on the client side. This is from my UMS client log:

```
API status was 404 for {"error":"E11000 duplicate key error collection: test.series_metadata index: imdbID_1 dup key: { imdbID: \"tt0080221\" }"}
, https://api.universalmediaserver.com/api/media/seriestitle?title=Galactica&year=1980
```

**Comment by SubJunk** [comment]
This was fixed in https://github.com/UniversalMediaServer/api/commit/6d5d330105d656a2346de7547d3b96ed33298cec
