### ISSUE TITLE
Log error: Missing path

### ISSUE THREAD

**Issue by SubJunk** [UniversalMediaServer/api#557]
Not sure how this is possible but the logs say:

```
Error: Missing path
    at OpenSubtitles.hash (/root/api/node_modules/opensubtitles-api/index.js:147:26)
    at /root/api/node_modules/opensubtitles-api/index.js:175:29
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at OpenSubtitles.osAPI.identify (/root/api/src/services/opensubtitles.ts:10:12)
    at Object.getByOsdbHash (/root/api/src/controllers/media.ts:60:33)
    at /root/api/src/routes/media.ts:9:3
    at bodyParser (/root/api/node_modules/koa-bodyparser/index.js:95:5)
    at /root/api/src/app.ts:73:3
    at /root/api/src/app.ts:66:3
    at /root/api/src/app.ts:30:5
```

It's a deprecated route but it would still be good to get it to give a ValidationError as it should be

**Comment by SubJunk** [comment]
This doesn't seem to happen anymore
