### ISSUE TITLE
Log error: totalSeasons: Cast to Number failed for value "NaN"

### ISSUE THREAD

**Issue by SubJunk** [UniversalMediaServer/api#595]
```
Error: SeriesMetadata validation failed: totalSeasons: Cast to Number failed for value "NaN" (type number) at path "totalSeasons"
    at ValidationError.inspect (/root/api/node_modules/mongoose/lib/error/validation.js:47:26)
    at formatValue (node:internal/util/inspect:757:19)
    at inspect (node:internal/util/inspect:336:10)
    at formatWithOptionsInternal (node:internal/util/inspect:1999:40)
    at formatWithOptions (node:internal/util/inspect:1881:10)
    at console.value (node:internal/console/constructor:335:14)
    at console.warn (node:internal/console/constructor:368:61)
    at consoleCall (<anonymous>)
    at /root/api/src/app.ts:59:15
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:94:5) {
  errors: {
    totalSeasons: CastError: Cast to Number failed for value "NaN" (type number) at path "totalSeasons"
        at SchemaNumber.cast (/root/api/node_modules/mongoose/lib/schema/number.js:373:11)
        at SchemaNumber.SchemaType.applySetters (/root/api/node_modules/mongoose/lib/schematype.js:1123:12)
        at model.$set (/root/api/node_modules/mongoose/lib/document.js:1284:20)
        at model.$set (/root/api/node_modules/mongoose/lib/document.js:1033:16)
        at model.Document (/root/api/node_modules/mongoose/lib/document.js:148:12)
        at model.Model (/root/api/node_modules/mongoose/lib/model.js:105:12)
        at new model (/root/api/node_modules/mongoose/lib/model.js:4902:15)
        at /root/api/node_modules/mongoose/lib/model.js:3157:22
        at /root/api/node_modules/mongoose/lib/model.js:3193:7
        at Array.forEach (<anonymous>)
        at /root/api/node_modules/mongoose/lib/model.js:3192:15
        at /root/api/node_modules/mongoose/lib/helpers/promiseOrCallback.js:32:5
        at new Promise (<anonymous>)
        at promiseOrCallback (/root/api/node_modules/mongoose/lib/helpers/promiseOrCallback.js:31:10)
        at Mongoose._promiseOrCallback (/root/api/node_modules/mongoose/lib/index.js:1149:10)
        at Function.create (/root/api/node_modules/mongoose/lib/model.js:3127:23) {
      stringValue: '"NaN"',
      messageFormat: undefined,
      kind: 'Number',
      value: NaN,
      path: 'totalSeasons',
      reason: AssertionError [ERR_ASSERTION]: The expression evaluated to a falsy value:
      
        assert.ok(!isNaN(val))
      
          at castNumber (/root/api/node_modules/mongoose/lib/cast/number.js:28:10)
          at SchemaNumber.cast (/root/api/node_modules/mongoose/lib/schema/number.js:371:12)
          at SchemaNumber.SchemaType.applySetters (/root/api/node_modules/mongoose/lib/schematype.js:1123:12)
          at model.$set (/root/api/node_modules/mongoose/lib/document.js:1284:20)
          at model.$set (/root/api/node_modules/mongoose/lib/document.js:1033:16)
          at model.Document (/root/api/node_modules/mongoose/lib/document.js:148:12)
          at model.Model (/root/api/node_modules/mongoose/lib/model.js:105:12)
          at new model (/root/api/node_modules/mongoose/lib/model.js:4902:15)
          at /root/api/node_modules/mongoose/lib/model.js:3157:22
          at /root/api/node_modules/mongoose/lib/model.js:3193:7
          at Array.forEach (<anonymous>)
          at /root/api/node_modules/mongoose/lib/model.js:3192:15
          at /root/api/node_modules/mongoose/lib/helpers/promiseOrCallback.js:32:5
          at new Promise (<anonymous>)
          at promiseOrCallback (/root/api/node_modules/mongoose/lib/helpers/promiseOrCallback.js:31:10)
          at Mongoose._promiseOrCallback (/root/api/node_modules/mongoose/lib/index.js:1149:10) {
        generatedMessage: true,
        code: 'ERR_ASSERTION',
        actual: false,
        expected: true,
        operator: '=='
      },
      valueType: 'number'
    }
  },
  _message: 'SeriesMetadata validation failed'
}
```

**Comment by SubJunk** [comment]
I thought I had fixed this. The stacktrace isn't very helpful for the context of the error.
