### ISSUE TITLE
Log error: TypeError: Cannot read properties of undefined

### ISSUE THREAD

**Issue by SubJunk** [UniversalMediaServer/api#698]
```
TypeError: Cannot read properties of undefined (reading 'length')
    at /root/api/node_modules/opensubtitles-api/index.js:203:52
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async OpenSubtitles.osAPI.identify (/root/api/src/services/opensubtitles.ts:11:12)
    at async Object.getFromOpenSubtitles (/root/api/src/services/external-api-helper.ts:522:33)
    at async Object.getVideo (/root/api/src/controllers/media.ts:464:31)
    at async /root/api/src/routes/media.ts:34:3
    at async bodyParser (/root/api/node_modules/koa-bodyparser/index.js:95:5)
    at async /root/api/src/app.ts:73:3
    at async /root/api/src/app.ts:66:3
```

**Comment by SubJunk** [comment]
This has been fixed
