### ISSUE TITLE
Log error: SyntaxError: Unexpected token

### ISSUE THREAD

**Issue by SubJunk** [UniversalMediaServer/api#699]
```
SyntaxError: Unexpected token ' in JSON at position 49
    at JSON.parse (<anonymous>)
    at Response.json (/root/api/node_modules/node-fetch/src/body.js:120:15)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async Client.omdbAPI.search (/root/api/src/services/omdb-api.ts:27:12)
    at async Object.getFromOMDbAPIV2 (/root/api/src/services/external-api-helper.ts:159:25)
    at async Object.getVideo (/root/api/src/controllers/media.ts:531:16)
    at async /root/api/src/routes/media.ts:34:3
    at async bodyParser (/root/api/node_modules/koa-bodyparser/index.js:95:5)
    at async /root/api/src/app.ts:73:3
```

**Comment by SubJunk** [comment]
This has been fixed
