### ISSUE TITLE
Log error: SeriesMetadata validation failed: imdbID: Path `imdbID` is required.

### ISSUE THREAD

**Issue by SubJunk** [UniversalMediaServer/api#700]
This one is interesting since maybe we should reassess whether IMDb IDs are required. Would be good to have better logging so we can see what the rest of the results looked like before this error
```
Error: SeriesMetadata validation failed: imdbID: Path `imdbID` is required.
    at ValidationError.inspect (/root/api/node_modules/mongoose/lib/error/validation.js:48:26)
    at formatValue (node:internal/util/inspect:761:19)
    at inspect (node:internal/util/inspect:338:10)
    at formatWithOptionsInternal (node:internal/util/inspect:2004:40)
    at formatWithOptions (node:internal/util/inspect:1886:10)
    at console.value (node:internal/console/constructor:327:14)
    at console.log (node:internal/console/constructor:363:61)
    at Object.getVideo (/root/api/src/controllers/media.ts:503:15)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5) {
```

**Comment by SubJunk** [comment]
This has been fixed
